const initializeUserFields = {
    firstName: {
        label: "First Name",
        name: "firstName",
        type: "text",
        sm: 4,
        required: true,
        value:"",
    },
    middleName: {
        label: "Middle Name",
        name: "middleName",
        type: "text",
        sm: 4,
        required: false,
        value:"",
    },
    lastName: {
        label: "Last Name",
        name: "lastName",
        type: "text",
        sm: 4,
        required: true,
        value:"",
    },
    phone: {
        label: "Phone",
        name: "phone",
        type: "tel",
        sm: 6,
        required: true,
        value:"",
    },
    email: {
        label: "Email",
        name: "email",
        type: "email",
        sm: 6,
        required: true,
        value:"",
    },
    password: {
        label: "Password",
        name: "password",
        type: "password",
        sm: 6,
        required: true,
        value:"",
    },
    repeat_password: {
        label: "Repeat Password",
        name: "repeat_password",
        type: "password",
        sm: 6,
        required: true,
        value:"",
    },
    imageAlt: {
        label: "Image Alt",
        name: "imageAlt",
        type: "text",
        sm: 6,
        required: false,
        value:"",
    },
    imageUrl: {
        label: "Image URL",
        name: "imageUrl",
        type: "url",
        sm: 6,
        required: false,
        value:"",
    },
    country: {
        label: "Country",
        name: "country",
        type: "text",
        sm: 4,
        required: true,
        value:"",
    },
    state: {
        label: "State",
        name: "state",
        type: "text",
        sm: 4,
        required: false,
        value:"",
    },
    city: {
        label: "City",
        name: "city",
        type: "text",
        sm: 4,
        required: true,
        value:"",
    },
    street: {
        label: "Street",
        name: "street",
        type: "text",
        sm: 4,
        required: true,
        value:"",
    },
    houseNumber: {
        label: "House Number",
        name: "houseNumber",
        type: "number",
        sm: 4,
        required: true,
        value:"",
    },
    zipCode: {
        label: "Zip",
        name: "zipCode",
        type: "text",
        sm: 4,
        required: false,
        value:"",
    },
};

export default initializeUserFields;